---

- name: Installing packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - python-passlib
  tags:
    - web
    - htpasswd
    - install

- name: Creating htpasswd folder
  file: >
    dest=/etc/htpasswd
    state=directory
    owner=root
    group=root
    mode=0755
  tags:
    - web
    - htpasswd
    - install
