---

- include: packages.yml

- include: config.yml

- include: service.yml

- { include: swarm_consul_client.yml, when: swarm_discovery is defined and swarm_discovery == 'consul' }

- { include: registrator_client.yml, when: swarm_discovery is defined and swarm_discovery == 'consul' }
