---
consul_version: 0.4.1
consul_archive: "consul_{{ consul_version }}_linux_amd64.zip"
consul_ui_archive: "consul_{{ consul_version }}_web_ui.zip"
consul_download: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_archive }}"
consul_ui_download: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_ui_archive }}"
consul_download_folder: /tmp
consul_home: /opt/consul
consul_config_dir: /etc/consul.d
consul_config_file: /etc/consul.conf
consul_log_file: /var/log/consul
consul_data_dir: "{{ consul_home }}/data"
consul_ui_dir: "{{ consul_home }}/dist"
consul_binary: consul
consul_user: consul
consul_group: consul
consul_domain: consul.
consul_is_server: false
consul_is_ui: false
consul_servers: ['127.0.0.1']
consul_log_level: "INFO"
consul_syslog: false
consul_rejoin_after_leave: true
consul_bind_address: "0.0.0.0"
consul_client_address: "127.0.0.1"
consul_node_name: "{{ ansible_default_ipv4['address'] }}"
consul_datacenter: "default"
consul_ui_require_auth: false
consul_ui_auth_user_file: /etc/htpasswd/consul
consul_enable_nginx_config: true
consul_disable_remote_exec: true
consul_install_dnsmasq: true
